### ISSUE TITLE
loading styles

### ISSUE THREAD

**Issue by Zt-freak** [microsoft/azure-devops-extension-sample#121]
Hi, I need help with loading styles. I can't load any css. I did not modify `Common.tsx` and both the lines `import "./Common.scss";` and `import "azure-devops-ui/Core/override.css";` are still in the file. However, React components get loaded in without any styling.

[link to my component](https://apodemus.gallerycdn.vsassets.io/extensions/apodemus/restrequestbutton/1.0.5/1667205859245/dist/RESTRequestButton/main.html)

**Comment by claudiogodoy99** [comment]
Hey @Zt-freak, I'm having the same issue, did you fixe up?

**Comment by Zt-freak** [comment]
> Hey @Zt-freak, I'm having the same issue, did you fixe up?
> 

What worked for me was upgrading packages to a newer version.
