### ISSUE TITLE
List

### ISSUE THREAD

**Issue by chris-to-pher** [microsoft/azure-devops-extension-sample#13]
Any chance to provide a List sample taking advantage of `azure-devops-ui`?

I can only find a `Pivot` which implements `office-ui-fabric-react`.

**Comment by nkirchem** [comment]
You can find samples under the List and Table components on the components site:
https://developer.microsoft.com/en-us/azure-devops/components/list
https://developer.microsoft.com/en-us/azure-devops/components/table
