### ISSUE TITLE
Hub, PivotBarItem and other components missing

### ISSUE THREAD

**Issue by mpseidel** [Microsoft/azure-devops-extension-sample#3]
Hey there,

thanks for building this sample repo - much apprecheated.

We were using the undocumented vss-ui package and for now it seems we can't switch to the `azure-devops-ui` package as some copmonents like `Hub` and `PivotBarItem` are missing in the new package.

Will those eventually be added to `azure-devops-ui` ?

**Comment by nkirchem** [comment]
The older internal vss-ui package was much more heavily based on Office Fabric, so some of the components have been replaced with others:

Hub was replaced by the Page component.
PivotBar was replaced by the TabBar component.
