### ISSUE TITLE
Adding dropdown in breadcrumb

### ISSUE THREAD

**Issue by shajusukumaran** [microsoft/azure-devops-extension-sample#30]
Hello Team,

How can we add dropdown in a breadcrumb for an extension (similar to what we have in the repos view)?

@nkirchem - any thoughts from your end?

Best regards,
Shaju

**Comment by nkirchem** [comment]
Hi @shajusukumaran that is not possible in the breadcrumb. The repo picker is not actually a breadcrumb item itself but extra content drawn at the end of the breadcrumb. We don't open that up to third-party extensions. The repo picker within the breadcrumb was there to backfill an existing need, but that UI pattern does not fit with the current design. I could see it changing at some point.

Thanks,
--Nick

**Comment by shajusukumaran** [comment]
Thanks @nkirchem for the quick turnaround.

**Comment by shajusukumaran** [comment]
@nkirchem is it possible to include a drop in the Header control. To achieve something similar to what is available in Repos to show the branch drop down and when a branch is selected the content changes accordingly.

**Comment by nkirchem** [comment]
@shajusukumaran sure, by using CustomHeader you can render whatever components you like. See https://developer.microsoft.com/en-us/azure-devops/components/header#advanced-header.

**Comment by shajusukumaran** [comment]
@nkirchem thank you for the help.
