### ISSUE TITLE
Add unit tests to example

### ISSUE THREAD

**Issue by charleszipp** [microsoft/azure-devops-extension-sample#63]
How can we unit test our extensions? I have tried doing this recently with Jest. Jest is unable to run load anything from azure-devops-ui library since its compiled to ES6 (not es2015). If there is a way to do that, it would be super helpful to have it in this repo.

**Comment by karelkral** [comment]
Guys, nobody from MS is responding here.  Azure DevOps is a very unsupported piece of development.
But I found and excellent article here: https://medium.com/javascript-in-plain-english/unit-testing-azure-devops-extensions-a1ed9ff69552
Try it.

**Comment by charleszipp** [comment]
Thanks for the link @karelkral. This is helpful. Also linking the example's source github repo which I found helpful as well https://github.com/h2floh/azure-dev-ops-react-ui-unit-testing. Would be great to have this reflected in this repo.

**Comment by h2floh** [comment]
Hey @karelkral and @charleszipp ,

just opened a PR for a minimal unit test sample #64
