### ISSUE TITLE
Can't hit git branches extensibility points

### ISSUE THREAD

**Issue by BiribiriJaNai** [Microsoft/azure-devops-extension-sample#7]
Hi,

I tried to add a sample to this project to hit some supposedly existing extensibility points, according to [the documentation](https://docs.microsoft.com/en-us/azure/devops/extend/reference/targets/overview?view=vsts#menus-and-toolbars). It's a basic copy / paste from the **Menu** sample, and looks like this:

_Actions/Actions.html_
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <body>
        <script type="text/javascript" src="Actions.js" charset="utf-8"></script>
    </body>
</html>
```

_Actions/Actions.ts_
```
import "es6-promise/auto";
import * as SDK from "azure-devops-extension-sdk";
import { CommonServiceIds, IHostDialogService  } from "azure-devops-extension-api";

SDK.register('sample-action', () => {
    return {
        execute: async(context: any) => {
            const dialogSvc = await SDK.getService<IHostDialogService>(CommonServiceIds.HostDialogService);
            dialogSvc.openMessageDialog(`Context: ${JSON.stringify(context)}`, { showCancel:false });
        }
    }
});

SDK.init();
```

and finally _Actions/Actions.json_
```
{
    "contributions": [
        {
            "id": "sample-action",
            "type": "ms.vss-web.action",
            "targets": [
                "ms.vss-admin-web.collection-overview-toolbar-menu",
                "ms.vss-admin-web.projects-grid-menu",
                "ms.vss-admin-web.project-overview-toolbar-menu",
                "ms.vss-admin-web.teams-grid-menu",
                "ms.vss-build-web.completed-build-menu",
                "ms.vss-build-web.build-definition-menu",
                "ms.vss-releaseManagement-web.release-definition-explorer-context-menu",
                "ms.vss-releaseManagement-web.release-definition-explorer-toolbar-menu",
                "ms.vss-releaseManagement-web.release-editor-tool-bar-menu",
                "ms.vss-code-web.source-grid-item-menu",
                "ms.vss-code-web.source-tree-item-menu",
                "ms.vss-code-web.source-item-menu",
                "ms.vss-code-web.git-branches-tree-menu",
                "ms.vss-code-web.git-branches-summary-grid-menu",
                "ms.vss-code-web.git-branches-summary-grid-diff-menu",
                "ms.vss-code-web.pull-request-action-menu"
            ],
            "properties": {
                "text": "Sample action",
                "uri": "dist/Actions/Actions.html",
                "icon": "static/sample-icon.png",
                "registeredObjectId": "sample-action"
            }
        }
    ]
}
```

Some of these targets are still working (build, release, source), others don't. And I don't understand why the git related ones are not responding (`ms.vss-code-web.git-branches-tree-menu`, `ms.vss-code-web.git-branches-summary-grid-menu` and `ms.vss-code-web.git-branches-summary-grid-diff-menu`).

I checked all possible actions in the following pages without any luck. I even switched to the old UI to be sure:
 - https://dev.azure.com/MY_ORG/_git/MY_PROJECT/branches
 - https://dev.azure.com/MY_ORG/MY_PROJECT/_settings/repositories

Did I miss something? Are these extensibility points still valid?
Thanks

**Comment by hross** [comment]
Thanks for bringing this to our attention. The "ms.vss-code-web.git-branches-tree-menu" contribution should exist in the branches page, but unfortunately looks like it was removed when the other two contributions were removed as part of a page redesign. The documentation is out of date and we will fix that as well. Sorry for the inconvenience. Expect us to ship the contribution in the branches tree point soon.
