### ISSUE TITLE
Add Widget sample

### ISSUE THREAD

**Issue by mikaelkrief** [microsoft/azure-devops-extension-sample#8]
Does it's possible to add the Widget sample please.

**Comment by stealthcold** [comment]
No widgets samples yet? 😞

**Comment by mpseidel** [comment]
Still no widget sample? 😿

**Comment by mguirao** [comment]
I would be very interested by a Widget sample

**Comment by pureliumy** [comment]
The only widget sample used the old SDK

**Comment by just-joshing** [comment]
Unfortunately widget development does not yet support the new SDK. Until that support is added there won't be a sample included here. Until then please refer to the [old SDK sample](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-dashboard-widget?view=azure-devops).

**Comment by andersforsgren** [comment]
Is there an issue somewhere that tracks this (adding widget support in the new SDK)?

**Comment by bworline** [comment]
> Is there an issue somewhere that tracks this (adding widget support in the new SDK)?

https://github.com/microsoft/azure-devops-extension-sdk/issues/22

**Comment by pureliumy** [comment]
> Is there an issue somewhere that tracks this (adding widget support in the new SDK)?

https://github.com/MicrosoftDocs/vsts-docs/issues/3848

**Comment by AppsatGIT** [comment]
Is there any sample available for Dashboard widget with configuration using new SDK?

**Comment by nardsqq** [comment]
Have you made any progress on the configuration part @AppsatGIT?

Posting to track this same issue for our team as suggested after filing a [ticket](https://developercommunity.visualstudio.com/t/Cannot-find-any-Documentation-for-Azure-/10443015). We're currently developing dashboard widgets (metrics) and looking to transition from the old SDK into the new SDK but it seems like only the documentation has been officially updated (without actual support to dashboard widgets). 

Just checking if there's any progress or actual development involving widgets?

**Comment by AppsatGIT** [comment]
@nardsqq Hi . I haven't found anything related to it. So no progress from my side.

**Comment by bworline** [comment]
> Is it still possible to make a widget sample with the new SDK?

I've just created a [PR](https://github.com/microsoft/azure-devops-extension-sample/pull/153).  You can use that while waiting for it to be merged.
