### ISSUE TITLE
Contribution visibility

### ISSUE THREAD

**Issue by nakah** [microsoft/azure-devops-extension-sample#82]
I would like to know if there's an API for enabling/disabling contribution visibility for specific users ?
For example, I would like to hide my Hub contribution on project hub (ms.vss-web.hub-group) based on some users status (active license)
I've seen this behavior with 7Pace Time Tracker extension where only users with assigned licences are able to see 7Pace's hub.

There must be some API somewhere but not documented enough :(

**Comment by karelkral** [comment]
The only way how to hide a feature I know is using the Features flags documented in this sample. But I understand that this is not for a licensing use. 

Azure DevOps development is the worst documented library ever. So many frustrations about it.
I think that there are many features in the extension manifest that are not documented. For example "constraints"...

**Comment by nakah** [comment]
@karelkral contraint seems to be limited to internal use reading this post: [https://rathertech.blogspot.com/2018/05/constrained-and-dignified.html](url)

I don't think it's the Feature flags sample the API I'm looking for.
After some deep dive, I think it's the licensing API that I need as you can define access per contribution [https://docs.microsoft.com/en-us/javascript/api/azure-devops-extension-api/contributionlicensingbehaviortype?view=azdevops-ext-latest](url)

But like other APIs, there is no sample on how to use it. [https://docs.microsoft.com/en-us/azure/devops/extend/develop/manifest?view=azure-devops#mark-an-extension-as-paid](url)

**Comment by nakah** [comment]
Continuing digging...
I've found this "restrictedTo" attribute on the manifest itself : [restrictedTo attribute](https://docs.microsoft.com/en-us/javascript/api/azure-devops-extension-api/extensionmanifest?view=azdevops-ext-latest#restrictedto).
However, it's not clear on how to use it :(

**Comment by karelkral** [comment]
Searching all GitHub code for "restrictedTo" and found this. I am afraid but this is not what you are searching for.

https://github.com/deliveredby/schemastore/blob/dfa957efe35a079230c2eff28c6f8ef1050a0109/src/schemas/json/vss-extension.json
````
        "restrictedTo": {
          "type": "array",
          "description": "Valid Values: https://docs.microsoft.com/en-us/azure/devops/extend/develop/public-project?view=azure-devops#contribution-visibility",
          "title": "Contribution visibility: By default, contributions are only visible to organization members. To give non-member users visibility to a contribution, set the restrictedTo attribute on that contribution. The value is a string array that lists which types of users should have visibility to the contribution",
          "items": {
            "type": "string",
            "description": "Valid Values: https://docs.microsoft.com/en-us/azure/devops/extend/develop/public-project?view=azure-devops#contribution-visibility",
            "title": "Contribution visibility: By default, contributions are only visible to organization members. To give non-member users visibility to a contribution, set the restrictedTo attribute on that contribution. The value is a string array that lists which types of users should have visibility to the contribution",
            "enum": [
              "member",
              "public",
              "anonymous"
            ]
          }
````

**Comment by nakah** [comment]
Thanks @karelkral but it seems that's not what I'm looking for.
I think your were right about the Feature option. After analyzing 7Pace extension, I found a REST call to FeatureManagement API when attributing a license to a user.
I think that's the way to go.

**Comment by nakah** [comment]
Ok, I've finally managed to hide contribution using Features.

**Comment by karelkral** [comment]
Can you share the essence of your solution, please?

**Comment by nakah** [comment]
In the manifest, you will need :
- "vso.features_write" scope
-  feature contribution   {
      "id": "feature-extensionEnabledForUser",
      "type": "ms.vss-web.feature",
      "description": "Enable feature for a specific user",
      "targets": [],
      "properties": {
        "name": "Feature",
        "userConfigurable": true,
        "hostConfigurable": false,
        "defaultState": false
      }
    },
- contraint on you hub-group contribution       
   "constraints": [
        {
          "name": "Feature",
          "properties": {
            "featureId": "PublisherID.ExtensionID.feature-extensionEnabledForUser"
          }
        }
      ]
- finally toggling value of feature using FeatureManagement API : setFeatureState(state, featureId, userId) in extension's settings page (hub contribution that targets "targets": ["ms.vss-web.collection-admin-hub-group"])

**Comment by karelkral** [comment]
Thank you, it will be very helpful!
