### ISSUE TITLE
run extension build failed on 'npm run build'

### ISSUE THREAD

**Issue by NadavShaked** [microsoft/azure-devops-extension-sample#87]
Hey,
I'm trying to create an extension by those commands:
npm install -g tfx-cli
tfx extension init

on empty folder as explained on readme

but I received this error:
error: Error: Command failed: npm run compile:dev
error: 'env' is not recognized as an internal or external command,
error: operable program or batch file.
error: npm ERR! code ELIFECYCLE
error: npm ERR! errno 1
error: npm ERR! 1321@1.0.0 test: `env TEST_REPORT_FILENAME=test-results.xml jest --verbose`
error: npm ERR! Exit status 1
error: npm ERR!
error: npm ERR! Failed at the 1321@1.0.0 test script.
error: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
error:
error: npm ERR! A complete log of this run can be found in:
error: npm ERR!     C:\Users\t-nashak\AppData\Roaming\npm-cache\_logs\2021-09-01T16_08_35_708Z-debug.log
error: npm ERR! code ELIFECYCLE
error: npm ERR! errno 1
error: npm ERR! 1321@1.0.0 compile:dev: `npm run clean && npm run test && webpack --mode development`
error: npm ERR! Exit status 1
error: npm ERR!
error: npm ERR! Failed at the 1321@1.0.0 compile:dev script.
error: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
error:
error: npm ERR! A complete log of this run can be found in:
error: npm ERR!     C:\Users\t-nashak\AppData\Roaming\npm-cache\_logs\2021-09-01T16_08_35_727Z-debug.log

this is my node js version: v12.18.3

do you know how can I fix it?

**Comment by karelkral** [comment]
I assume that you are running on Windows.  There is not `env` command on Windows, 
* so change your scripts in `package.json` to use windows `set` command. ` "test": "set TEST_REPORT_FILENAME=test-results.xml && jest --verbose"`
* Or the second way is using [cross-env](https://www.npmjs.com/package/cross-env) plugin which is multi-platform. Then my script is: `"test": "cross-env TEST_REPORT_FILENAME=test-results.xml && jest --verbose"`

**Comment by NadavShaked** [comment]
it works, thanks!
