### ISSUE TITLE
Is this a replacement of the vss-* libraries?

### ISSUE THREAD

**Issue by tomkuijsten** [Microsoft/azure-devops-extension-sample#9]
According to this documentation:

https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=vsts

We should install the "vss-web-extension-sdk", however you are using "azure-devops-extension-sdk" How are these two different?

**Comment by nkirchem** [comment]
This is the replacement. The older vss-web-extension-sdk will continue to work indefinitely. We will be working on updating that documentation to point here as the new/recommended model, but it will take some more time until we land there. We have a new doc site for our new extension UI components that we hope to launch within the next few weeks.

**Comment by shajusukumaran** [comment]
Can we use both "vss-web-extension-sdk" and "azure-devops-extension-sdk" in the same project?

**Comment by nkirchem** [comment]
@shajusukumaran Yes, you can use both in the same extension, but only one version of the SDK should be loaded in a given iframe. So, for example, your extension could have two different hubs, and one hub uses the old SDK and the other uses the new one. Or you could have a dashboard widget using the old SDK but a menu item contribution using the new one. You just can't mismatch SDKs within the same contribution.

Hope that helps. Let me know if that needs further clarification.

**Comment by shajusukumaran** [comment]
@nkirchem Thanks! got it.
